### ISSUE TITLE
[bug] : unable to load packages

### ISSUE THREAD

**Issue by DIGIX666** [gfanton/gnopls#1]
Hey @gfanton 
I'm trying to use `gnopls` but after installing this command `go install github.com/gfanton/gnopls@latest`, I open a gno file and this error appears in my VSCode 

Do you know why I get this error?

```
Error loading workspace: unable to load packages [[/Users/theodub/Documents/GNO/fork/gno_thox/... builtin]]: gnopackagesdriver: exec: "gnopackagesdriver": executable file not found in $PATH:
```
But I don't have this error if I clone the repo and run `make install` for have `gnopackagesdriver`

**Comment by gfanton** [comment]
Yes, when you run `go install github.com/gfanton/gnopls@latest`, you are only installing `gnopls`. You also need to install `gnopackagesdriver` for it to function properly. 

Following this logic, you can install both remotely, but you must execute both commands:

-  `go install github.com/gfanton/gnopls/gnopackagesdriver@latest`
-  `go install github.com/gfanton/gnopls@latest`

to ensures that `gnopls` works correctly.

**Comment by DIGIX666** [comment]
Another problem after installing `gnopls` I didn't get any error number in my code. Is this due to `gnopls`?

![image](https://github.com/user-attachments/assets/97aa9d35-55c6-4f75-b905-1b3bd8c2a14c)
![image](https://github.com/user-attachments/assets/53963280-a6fc-43dd-b2c4-69978031da44)

**Comment by n0izn0iz** [comment]
> I have a question, should an improvement be made so that the links don't tend towards go.dev?

yes I opened an issue for it here #4 

> It's good I solved the problem by deleting the GNOROOTs in the GNO extension workspace and uninstalling and reinstalling

good to know, closing
